analytics: {}
color:
  brandColors:
    - '#f0f5f9'
    - '#85c0e2'
    - '#0a0907'
    - '#2d3224'
    - '#9e929e'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 1
  saturation: 0.499155
cta: {}
layout_spectrum: 1
name: NVshoots
opengraph: {}
purpose: []
typography_spectrum: 0.9798302040435374
