name: NVshoots
favicon: null
layout_spectrum: 0.23137589660473168
typography_spectrum: 0.9798302040435374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.45937905507162213
  lightness: 0.2652758019976318
  saturation: 0.48076529148966074
  rhythmicContrast: 0.9770950297825038
purpose: []
