name: NVshoots
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9798302040435374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f6fc'
    - '#2d2321'
    - '#9e989c'
    - '#6f5e57'
    - '#d52b19'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.9770950297825038
purpose: []
